# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conreality/rpc/common.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Conreality.RPC.EmptyRequest" do
  end
  add_message "Conreality.RPC.EmptyResponse" do
  end
  add_message "Conreality.RPC.IDResponse" do
    optional :id, :uint64, 1
  end
  add_message "Conreality.RPC.PingRequest" do
  end
  add_message "Conreality.RPC.PongResponse" do
  end
  add_message "Conreality.RPC.HelloRequest" do
    optional :version, :string, 1
  end
  add_message "Conreality.RPC.HelloResponse" do
    optional :version, :string, 1
  end
end

module Conreality
  module RPC
    EmptyRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Conreality.RPC.EmptyRequest").msgclass
    EmptyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("Conreality.RPC.EmptyResponse").msgclass
    IDResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("Conreality.RPC.IDResponse").msgclass
    PingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Conreality.RPC.PingRequest").msgclass
    PongResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("Conreality.RPC.PongResponse").msgclass
    HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Conreality.RPC.HelloRequest").msgclass
    HelloResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("Conreality.RPC.HelloResponse").msgclass
  end
end
