# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conreality/rpc/master.proto

require 'google/protobuf'

require 'conreality/rpc/model_pb'
require 'conreality/rpc/common_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Conreality.RPC.AuthRequest" do
    optional :player_nick, :string, 1
  end
  add_message "Conreality.RPC.AuthResponse" do
    optional :session_id, :uint64, 1
  end
  add_message "Conreality.RPC.SendEventRequest" do
    optional :session_id, :uint64, 1
    optional :predicate, :string, 2
    optional :subject_uuid, :string, 3
    optional :object_uuid, :string, 4
  end
  add_message "Conreality.RPC.SendMessageRequest" do
    optional :session_id, :uint64, 1
    optional :text, :string, 2
  end
  add_message "Conreality.RPC.UpdatePlayerRequest" do
    optional :session_id, :uint64, 1
    optional :heartbeat, :uint32, 2
  end
end

module Conreality
  module RPC
    AuthRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Conreality.RPC.AuthRequest").msgclass
    AuthResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("Conreality.RPC.AuthResponse").msgclass
    SendEventRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Conreality.RPC.SendEventRequest").msgclass
    SendMessageRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Conreality.RPC.SendMessageRequest").msgclass
    UpdatePlayerRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Conreality.RPC.UpdatePlayerRequest").msgclass
  end
end
