# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: conreality/rpc/master.proto for package 'Conreality.RPC'
# Original file comments:
# This is free and unencumbered software released into the public domain. 
#

require 'grpc'
require 'conreality/rpc/master_pb'

module Conreality
  module RPC
    module Public
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'Conreality.RPC.Public'

        rpc :Authenticate, AuthRequest, AuthResponse
        rpc :Bye, EmptyRequest, EmptyResponse
        rpc :Hello, HelloRequest, HelloResponse
        rpc :Ping, PingRequest, PongResponse
      end

      Stub = Service.rpc_stub_class
    end
    module Session
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'Conreality.RPC.Session'

        rpc :Ping, PingRequest, PongResponse
        rpc :SendEvent, SendEventRequest, IDResponse
        rpc :SendMessage, SendMessageRequest, IDResponse
        rpc :UpdatePlayer, UpdatePlayerRequest, EmptyResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
