# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conreality/rpc/model.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Conreality
  module RPC
  end
end
